AUTHOR_NAME="Jérémie DECOCK"
AUTHOR_EMAIL="jd.jdhp@gmail.com"
AUTHOR_WEB_SITE="www.jdhp.org"

COPYRIGHT_NOTICE="Copyright (c) 2016,2017 ${AUTHOR_NAME} (${AUTHOR_WEB_SITE})"

DOCUMENT_DATE="November 1, 2016"
INSTITUTE=""
DOCUMENT_SUBJECT="Some snippets for reveal.js"
DOCUMENT_KEYWORDS="reveal.js,snippets"

DOCUMENT_TITLE="Reveal.js snippets"
DOCUMENT_SUBTITLE=""
DOCUMENT_FILE_BASE_NAME="revealjs_snippets"

DOCUMENT_GITHUB_ACCOUNT="jdhp-docs"
DOCUMENT_GITHUB_REPOSITORY_NAME="revealjs-snippets"

DOCUMENT_GITHUB_URL="https://github.com/${DOCUMENT_GITHUB_ACCOUNT}/${DOCUMENT_GITHUB_REPOSITORY_NAME}"
DOCUMENT_ISSUE_TRACKER_URL="https://github.com/${DOCUMENT_GITHUB_ACCOUNT}/${DOCUMENT_GITHUB_REPOSITORY_NAME}/issues"

DOCUMENT_WEB_SITE_URL="http://www.jdhp.org/documentation_en.html#${DOCUMENT_FILE_BASE_NAME}"
DOCUMENT_HTML_URL="http://www.jdhp.org/docs/${DOCUMENT_FILE_BASE_NAME}/${DOCUMENT_FILE_BASE_NAME}.html"
DOCUMENT_PDF_URL="http://www.jdhp.org/dl/pdf/${DOCUMENT_FILE_BASE_NAME}.pdf"

HTML_TMP_DIR="html_tmp"
