TODO_AUTHOR_NAME="Jérémie DECOCK"
TODO_AUTHOR_EMAIL="jd.jdhp@gmail.com"
TODO_AUTHOR_WEB_SITE="www.jdhp.org"

TODO_COPYRIGHT_NOTICE="Copyright (c) 2016 ${TODO_AUTHOR_NAME} (${TODO_AUTHOR_WEB_SITE})"

TODO_DOCUMENT_DATE="November 1, 2016"
TODO_INSTITUTE=""
TODO_DOCUMENT_SUBJECT="Some snippets for reveal.js"
TODO_DOCUMENT_KEYWORDS="reveal.js,snippets"

TODO_DOCUMENT_TITLE="Reveal.js snippets"
TODO_DOCUMENT_SUBTITLE=""
TODO_DOCUMENT_FILE_BASE_NAME="revealjs_snippets"

TODO_DOCUMENT_GITHUB_ACCOUNT="jdhp-docs"
TODO_DOCUMENT_GITHUB_REPOSITORY_NAME="revealjs-snippets"

TODO_DOCUMENT_GITHUB_URL="https://github.com/${TODO_DOCUMENT_GITHUB_ACCOUNT}/${TODO_DOCUMENT_GITHUB_REPOSITORY_NAME}"
TODO_DOCUMENT_ISSUE_TRACKER_URL="https://github.com/${TODO_DOCUMENT_GITHUB_ACCOUNT}/${TODO_DOCUMENT_GITHUB_REPOSITORY_NAME}/issues"

TODO_DOCUMENT_WEB_SITE_URL="http://www.jdhp.org/documentation_en.html#${TODO_DOCUMENT_FILE_BASE_NAME}"
TODO_DOCUMENT_HTML_URL="http://www.jdhp.org/docs/${TODO_DOCUMENT_FILE_BASE_NAME}/${TODO_DOCUMENT_FILE_BASE_NAME}.html"
TODO_DOCUMENT_PDF_URL="http://www.jdhp.org/dl/pdf/${TODO_DOCUMENT_FILE_BASE_NAME}.pdf"

TODO_HTML_TMP_DIR="html_tmp"
